service: sia-email

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3001

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'develop'}
  region: us-east-1
  profile: matersoft
  environment:
    CUSTOM: ${file(./src/config/${self:provider.stage}.js)}

functions:
  sender:
    handler: handle.sender
    timeout: 400
    events:
      - http:
          path: sender/
          method: post
