service: email

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3001

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'develop'}
  region: us-east-1
  profile:  matersoft
  environment:
    CUSTOM: ${file(./src/config/${self:provider.stage}.js)}


functions:
  handle:
    handler: handle.run
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /{correo}/{asunto}/{mensaje}/{template}
          method: GET
          cors: true

